config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/openaire/DSpace:
      branch: master
      repo: https://github.com/openaire/DSpace.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/openaire/DSpace git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-aqua-impala.sh
        container: qc.acc_chewy-amber-magpie
  QC.Doc:
    repos:
      github.com/openaire/DSpace find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-xanthic-crab.sh
        container: qc.doc_jumpy-aquamarine-schnauzer
      github.com/openaire/DSpace git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-platinum-boar.sh
        container: qc.doc_wiggy-cardinal-quokka
      github.com/openaire/DSpace markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-indigo-fox.sh
        container: qc.doc_tacky-ecru-markhor
  QC.Lic:
    repos:
      github.com/openaire/DSpace licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-blue-snake.sh
        container: qc.lic_foggy-coral-opossum
  QC.Sty:
    repos:
      github.com/openaire/DSpace checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cinnabar-horse.sh
        container: qc.sty_boozy-chocolate-paradise
      github.com/openaire/DSpace hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-silver-hound.sh
        container: qc.sty_stinky-pink-tetra
      github.com/openaire/DSpace jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-gold-ant.sh
        container: qc.sty_clammy-lemon-hyena
  QC.Ver:
    repos:
      github.com/openaire/DSpace get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-aquamarine-bullfrog.sh
        container: qc.ver_stinky-puce-balinese
timeout: 5400
